<?php
/**
 * Implements hook_install().
 */
function personality_test_install() {
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['personality_test']);
  add_custom_fields();
}

/**
 * Implements hook_uninstall().
 */
function personality_test_uninstall() {
  $ournewtype = 'personality_test';
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => $ournewtype));
  $nodeids = array();
  foreach ($result as $row) {
    $nodeids[] = $row->nid;
  }
  node_delete_multiple($nodeids);
  delete_custom_fields();
  node_type_delete($ournewtype);
  field_purge_batch(500);
}

function add_custom_fields() {
  foreach (_personality_test_fields() as $field) {
    field_create_field($field['field']);
    $field['instance']['entity_type'] = 'node';
    $field['instance']['bundle'] = 'personality_test';
    field_create_instance($field['instance']);
  }
}
 
function delete_custom_fields() {
  foreach (_personality_test_fields() as $field) {
    field_delete_field($field['field']['field_name']);
  }
  $instances = field_info_instances('node', 'personality_test');
  foreach ($instances as $instance_name => $fieldinstance) {
    field_delete_instance($fieldinstance);
  }
}

function _personality_test_fields() {
  $t = get_t();
  return array(
    array(
      'field' => array(
        'field_name' => 'personality_test_price',
        'label' => $t('Price of the Personality Test'),
        'type' => 'text'
      ),
      'instance' => array(
        'field_name' => 'personality_test_price',
        'type' => 'text',
        'label' => $t('Price of the Personality Test'),
        'widget' => array('type' => 'text_textfield'),
        'required' => TRUE,
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
          )
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_quantity',
        'label' => $t('Quantity of the Personality Test'),
        'type' => 'text',
      ),
      'instance' => array(
        'field_name' => 'personality_test_quantity',
        'type' => 'text',
        'label' => $t('Quantity of the Personality Test'),
        'widget' => array('type' => 'text_textfield'),
        'display' => array(
          'default' => array(
            'label' => 'hidden',
            'type' => 'text_default'
          )
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_answers',
        'label' => $t('Personality Test Answers'),
        'type' => 'field_collection'
      ),
      'instance' => array(
        'field_name' => 'personality_test_answers',
        'type' => 'field_collection',
        'label' => $t('Personality Test Answers'),
        'widget' => array('type' => 'field_collection_embed'), // field_collection_hidden
        'display' => array(
          'default' => array(
            'label' => 'hidden',
            'type' => 'field_collection_fields' // field_collection_list, _view, _fields, hidden
          )
        )
      ),
    ),
  );
}