<?php
/**
 * Implements hook_node_info()
 */
function personality_test_node_info() {
  return array(
    // machine_name
    'personality_test' => array(
      'name' => t('Personality Test'),
      'base' => 'personality_test', // name of module
      'description' => t('Create custom personality tests.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
    )
  );
}

/**
 * Implements hook_form(). Which is only the node form.
 */
function personality_test_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_node_view()
 */
function personality_test_node_view($node, $view_mode, $langcode) {
  // Maybe tell node to load in a view mode dependent on cookie inside here ???
  // and hide the normal fields from view mode here ???
  // will the form still work then ???
  
  $form = drupal_get_form('personality_test', $node);
  $node->content['personality_test'] = array(
    '#markup' => drupal_render($form),
  );
}

/**
 * Our actual form
 */
function personality_test($form, &$form_state, $node) {
  // get field collection items from node
  $items = $node->personality_test_questions[LANGUAGE_NONE];
  // call helper to build form elements from field collection items
  $elements = _personality_test_build_form($items);
  foreach ($elements as $element => $controls) {
    $form[$element] = $controls;
  }
  // append submit button
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Evaluation'),
  );
  return $form;
}

function personality_test_submit($form, &$form_state) {

}

/**
 * Helper function to build form elements from field collection items
 */
function _personality_test_build_form($items) {
  $i = 0;
  foreach ($items as $item) {
    $i++;
    $index = sprintf("%02d", $i);
    // get questions, get options
    $item_id = $item['value'];
    $entity = entity_load('field_collection_item', array($item_id));
    $question = $entity[$item_id]->personality_test_question_body[LANGUAGE_NONE][0]['value'];
    $option_items = $entity[$item_id]->personality_test_answers[LANGUAGE_NONE];
    $options = _personality_test_options($option_items);
    // put everything together
    $elements['question_'.$index] = array(
      '#type' => 'radios',
      '#title' => $question,
      '#options' => $options
    );
  }
  return $elements;
}

/**
 * Helper function to build radio options from field collection items
 */
function _personality_test_options($option_items) {
  $options = array();
  foreach ($option_items as $item) {
    $item_id = $item['value'];
    $entity = entity_load('field_collection_item', array($item_id));
    $answer = $entity[$item_id]->personality_test_answer_body[LANGUAGE_NONE][0]['value'];
    $key = $entity[$item_id]->personality_test_answer_map[LANGUAGE_NONE][0]['value'];
    $options[$key] = $answer;
  }
  return $options;
}



