<?php
/**
 * Implements hook_install().
 */
function personality_test_install() {
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['personality_test']);
  add_custom_fields();
}

/**
 * Implements hook_uninstall().
 */
function personality_test_uninstall() {
  $ournewtype = 'personality_test';
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => $ournewtype));
  $nodeids = array();
  foreach ($result as $row) {
    $nodeids[] = $row->nid;
  }
  node_delete_multiple($nodeids);
  delete_custom_fields();
  node_type_delete($ournewtype);
  field_purge_batch(500);
}

function add_custom_fields() {
  foreach (_personality_test_installed_fields() as $field) {
    field_create_field($field);
  }
  foreach (_personality_test_installed_instances() as $fieldinstance) {
    $fieldinstance['entity_type'] = 'node';
    $fieldinstance['bundle'] = 'personality_test';
    field_create_instance($fieldinstance);
  }
}
 
function delete_custom_fields() {
  foreach (array_keys(_personality_test_installed_fields()) as $field) {
    field_delete_field($field);
  }
  $instances = field_info_instances('node', 'personality_test');
  foreach ($instances as $instance_name => $fieldinstance) {
    field_delete_instance($fieldinstance);
  }
}

function _personality_test_installed_fields() {
  $t = get_t();
  return array(
    'personality_test_price' => array(
      'field_name' => 'personality_test_price',
      'label' => $t('Price of the Personality Test'),
      'type' => 'text'
    ),
    'personality_test_quantity' => array(
      'field_name' => 'personality_test_quantity',
      'label' => $t('Quantity of the Personality Test'),
      'type' => 'text'
    ),
    'personality_test_answers' => array(
      'field_name' => 'personality_test_answers',
      'label' => $t('Personality Test Answers'),
      'type' => 'field_collection'
    ),
  );
}

function _personality_test_installed_instances() {
  $t = get_t();
  return array(
    'personality_test_price' => array(
      'field_name' => 'personality_test_price',
      'type' => 'text',
      'label' => $t('Price of the Personality Test'),
      'widget' => array('type' => 'text_textfield'),
      'display' => array(
        'default' => array(
          'label' => 'hidden', // hidden, inline, above
          'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
        )
      )
    ),

    'personality_test_quantity' => array(
      'field_name' => 'personality_test_quantity',
      'type' => 'text',
      'label' => $t('Quantity of the Personality Test'),
      'widget' => array('type' => 'text_textfield'),
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'text_default'
        )
      )
    ),

    'personality_test_answers' => array(
      'field_name' => 'personality_test_answers',
      'type' => 'field_collection',
      'label' => $t('Personality Test Answers'),
      'widget' => array('type' => 'field_collection_embed'), // field_collection_hidden
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'field_collection_fields' // field_collection_list, _view, _fields, hidden
        )
      )
    ),

  );
}