<?php

/**
 * Implements hook_install().
 */
function personality_test_install() {
  node_types_rebuild();
  $types = node_type_get_types();

  // Add a body field
  // node_add_body_field($types['personality_test']);
  
  // Add custom fields
  add_custom_fields();

  // Default to not to be promoted
  variable_set('node_options_personality_test', array('status'));

  // Disable comments
  variable_set('comment_personality_test', COMMENT_NODE_CLOSED);

  // Hide date and author information
  variable_set('node_submitted_personality_test', FALSE);

  // Disable node preview
  variable_set('node_preview_personality_test', 0);

  // Disable menu entry
  variable_set('menu_options_personality_test', array(0));

  // more information: https://www.drupal.org/node/1169864
}

/**
 * Implements hook_uninstall().
 */
function personality_test_uninstall() {
  $ournewtype = 'personality_test';
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => $ournewtype));
  $nodeids = array();

  foreach ($result as $row) {
    $nodeids[] = $row->nid;
  }

  node_delete_multiple($nodeids);

  // Delete custom fields
  delete_custom_fields();

  // Delete the node type
  node_type_delete($ournewtype);

  // ??? Big question mark
  field_purge_batch(500);
}

/**
 * Helper function to install all fields on hook_install()
 */
function add_custom_fields() {

  foreach (_personality_test_fields() as $field) {

    // Needs at least a field_name and a type
    field_create_field($field['field']);

    // Needs at least a field_name, an entity_type and a bundle
    field_create_instance($field['instance']);
  }
}

/**
 * Helper function to delete all on hook_uninstall()
 */
function delete_custom_fields() {

  foreach (_personality_test_fields() as $field) {

    // Needs a field_name only
    field_delete_field($field['field']['field_name']);

    // Needs at least a field_name, an entity_type and a bundle
    field_delete_instance($field['instance']);
  }
}

/**
 * Helper function to define custom fields
 * @return [array] [An array of fields, their instances and further field settings]
 */
function _personality_test_fields() {
  $t = get_t();
  return array(
    // Teaser Text
    array(
      'field' => array(
        'field_name' => 'personality_test_body',
        'label' => $t('Body'),
        'type' => 'text_long'
      ),
      'instance' => array(
        'field_name' => 'personality_test_body',
        'entity_type' => 'node',
        'bundle' => 'personality_test',
        'label' => $t('Body'),
        'widget' => array('type' => 'text_textarea'),
        'display' => array(
          'default' => array( // view mode
            'label' => 'hidden',
            'type' => 'text_default'
          ),
          'result' => array( // view mode
            'label' => 'hidden',
            'type' => 'text_default'
          ),
        )
      ),
    ),
    // Image
    array(
      'field' => array(
        'field_name' => 'personality_test_image',
        'label' => $t('Image'),
        'type' => 'image'
      ),
      'instance' => array(
        'field_name' => 'personality_test_image',
        'entity_type' => 'node',
        'bundle' => 'personality_test',
        'label' => $t('Image'),
        'widget' => array('type' => 'image_image'),
        'display' => array(
          'default' => array( // view mode
            'label' => 'hidden',
            'type' => 'image'
          ),
          'result' => array( // view mode
            'label' => 'hidden',
            'type' => 'image'
          ),
        )
      ),
    ),
    // Results
    array(
      'field' => array(
        'field_name' => 'personality_test_results',
        'label' => $t('Personality Test Results (A, B and C)'),
        'cardinality' => 3,
        'type' => 'field_collection'
      ),
      'instance' => array(
        'field_name' => 'personality_test_results',
        'entity_type' => 'node',
        'bundle' => 'personality_test',
        'label' => $t('Personality Test Results (A, B and C)'),
        'widget' => array('type' => 'field_collection_embed'), // field_collection_hidden
        'display' => array(
          'default' => array( // view mode, hide on default but display on result
            'label' => 'hidden',
            'type' => 'hidden' // field_collection_list, _view, _fields, hidden
          ),
          'result' => array( // view mode
            'label' => 'hidden',
            'type' => 'field_collection_fields' // field_collection_list, _view, _fields, hidden
          ),
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_result_heading',
        'label' => $t('Heading'),
        'type' => 'text'
      ),
      'instance' => array(
        'field_name' => 'personality_test_result_heading',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_results',
        'label' => $t('Heading'),
        'widget' => array('type' => 'text_textfield'),
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
          )
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_result_body',
        'label' => $t('Body'),
        'type' => 'text_long'
      ),
      'instance' => array(
        'field_name' => 'personality_test_result_body',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_results',
        'label' => $t('Body'),
        'widget' => array('type' => 'text_textarea'),
        'required' => TRUE,
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
          )
        )
      ),
    ),
    // Questions
    array(
      'field' => array(
        'field_name' => 'personality_test_questions',
        'label' => $t('Personality Test Questions'),
        'cardinality' => FIELD_CARDINALITY_UNLIMITED,
        'type' => 'field_collection'
      ),
      'instance' => array(
        'field_name' => 'personality_test_questions',
        'entity_type' => 'node',
        'bundle' => 'personality_test',
        'label' => $t('Personality Test Questions'),
        'widget' => array('type' => 'field_collection_embed'), // field_collection_hidden
        'display' => array(
          'default' => array( // view mode
            'label' => 'hidden',
            'type' => 'hidden' // hide fields since we'll have a form instead
          ),
          'result' => array( // view mode
            'label' => 'hidden',
            'type' => 'hidden' // hide fields since we'll have a form instead
          )
        ),
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_question_body',
        'label' => $t('Question'),
        'type' => 'text_long'
      ),
      'instance' => array(
        'field_name' => 'personality_test_question_body',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_questions',
        'label' => $t('Question'),
        'widget' => array('type' => 'text_textarea'),
        'required' => TRUE,
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
          )
        )
      ),
    ),
    // Answers
    array(
      'field' => array(
        'field_name' => 'personality_test_answers',
        'label' => $t('Answers'),
        'cardinality' => 3,
        'type' => 'field_collection'
      ),
      'instance' => array(
        'field_name' => 'personality_test_answers',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_questions',
        'label' => $t('Answers'),
        'widget' => array('type' => 'field_collection_embed'),
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'field_collecton_fields'
          )
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_answer_body',
        'label' => $t('Answer'),
        'type' => 'text_long'
      ),
      'instance' => array(
        'field_name' => 'personality_test_answer_body',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_answers',
        'label' => $t('Answer'),
        'widget' => array('type' => 'text_textarea'),
        'required' => TRUE,
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'text_default' // text_default, text_plain, text_trimmed, hidden
          )
        )
      ),
    ),
    array(
      'field' => array(
        'field_name' => 'personality_test_answer_map',
        'label' => $t('Map to Result A, B or C'),
        'type' => 'list_integer',
        'settings' => array(
          'allowed_values' => array('A', 'B', 'C'),
        ),
      ),
      'instance' => array(
        'field_name' => 'personality_test_answer_map',
        'entity_type' => 'field_collection_item',
        'bundle' => 'personality_test_answers',
        'label' => $t('Map to Result A, B or C'),
        'widget' => array('type' => 'options_select'),
        'required' => TRUE,
        'display' => array(
          'default' => array(
            'label' => 'hidden', // hidden, inline, above
            'type' => 'list_default' // list_default, list_key, hidden
          )
        )
      ),
    ),
  );
}
